name: farrier_log_app
description: A farrier logbook with offline-first data and calendar integration.
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  provider: ^6.1.2
  drift: ^2.17.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.3
  path: ^1.9.0
  image_picker: ^1.1.1
  add_2_calendar: ^3.0.1
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.17.0
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    # add assets here if needed, e.g. images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
